name = "MomentOpt"
uuid = "5036cc39-ae6e-5f00-bcd6-dacb213bf05a"
authors = ["Tillmann Weisser"]
repo = "https://github.com/lanl-ansi/MomentOpt.jl"
version = "0.1.0"

[deps]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
DynamicPolynomials = "7c1d4256-1411-5781-91ec-d7bc3513ac07"
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MathOptInterface = "b8f27783-ece8-5eb3-8dc8-9495eed66fee"
MultivariateBases = "be282fd4-ad43-11e9-1d11-8bd9d7e43378"
MultivariateMoments = "f4abf1af-0426-5881-a0da-e2f168889b5e"
MultivariatePolynomials = "102ac46a-7ee4-5c85-9060-abc95bfdeaa3"
MutableArithmetics = "d8a4904e-b15c-11e9-3269-09a3773c0cb0"
PolyJuMP = "ddf597a6-d67e-5340-b84c-e37d84115374"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
SCS = "c946c3f1-0d1f-5ce8-9dea-7daa1f7e2d13"
SemialgebraicSets = "8e049039-38e8-557d-ae3a-bc521ccf6204"
SumOfSquares = "4b9e565b-77fc-50a5-a571-1244f986bda1"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
DynamicPolynomials = "~0.3"
JuMP = "~0.21"
MathOptInterface = "~0.9"
MultivariateBases = "~0.1"
MultivariateMoments = "~0.3"
MultivariatePolynomials = "~0.3"
MutableArithmetics = "~0.2"
PolyJuMP = "~0.4"
SemialgebraicSets = "~0.2"
SumOfSquares = "~0.4"

[extras]
SCS = "c946c3f1-0d1f-5ce8-9dea-7daa1f7e2d13"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["SCS"]
