name = "MomentOpt"
uuid = "5036cc39-ae6e-5f00-bcd6-dacb213bf05a"
authors = ["Tillmann Weisser"]
repo = "https://github.com/lanl-ansi/MomentOpt.jl"
version = "0.0.1"

[deps]
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
MathOptInterface = "b8f27783-ece8-5eb3-8dc8-9495eed66fee"
MultivariatePolynomials = "102ac46a-7ee4-5c85-9060-abc95bfdeaa3"
PolyJuMP = "ddf597a6-d67e-5340-b84c-e37d84115374"
SemialgebraicSets = "8e049039-38e8-557d-ae3a-bc521ccf6204"
SumOfSquares = "4b9e565b-77fc-50a5-a571-1244f986bda1"

[compat]
DynamicPolynomials = "~0.3"
JuMP = "~0.19"
MathOptInterface = "~0.8"
MultivariatePolynomials = "~0.3.1"
PolyJuMP = "~0.3"
SemialgebraicSets = "~0.1"
SumOfSquares = "~0.3"

[extras]
DynamicPolynomials = "7c1d4256-1411-5781-91ec-d7bc3513ac07"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
CSDP = "0a46da34-8e4b-519e-b418-48813639ff34"

[targets]
test = ["Test", "DynamicPolynomials", "CSDP"]
